//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colegio
    {
        public int IdColegio { get; set; }
        public int SIE { get; set; }
        public string Nombre { get; set; }
        public string Resolucion { get; set; }
        public System.DateTime FechaResolucion { get; set; }
        public int Telefono { get; set; }
        public string Direccion { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> IdDistrito { get; set; }
        public Nullable<int> IdTipoColegio { get; set; }
        public Nullable<int> IdLogo { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public int Estado { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        public virtual Logo Logo { get; set; }
        public virtual TipoColegio TipoColegio { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
