//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diploma
    {
        public int IdDiploma { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> IdEstudiante { get; set; }
        public int Estado { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
