//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legalizacion
    {
        public int IdLegalizacion { get; set; }
        public int NroReciboBco { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaVerificacion { get; set; }
        public long Cantidad { get; set; }
        public string Detalle { get; set; }
        public string FirmaDigital { get; set; }
        public int IdEstudiante { get; set; }
        public int Estado { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
