//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMinisterioEntities : DbContext
    {
        public dbMinisterioEntities()
            : base("name=dbMinisterioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Colegio> Colegio { get; set; }
        public virtual DbSet<CuentaUsuario> CuentaUsuario { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Diploma> Diploma { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<FuncionarioSeduca> FuncionarioSeduca { get; set; }
        public virtual DbSet<Gestion> Gestion { get; set; }
        public virtual DbSet<Legalizacion> Legalizacion { get; set; }
        public virtual DbSet<Logo> Logo { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Privilegio> Privilegio { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<TipoColegio> TipoColegio { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<PersonalColegio> PersonalColegio { get; set; }
    }
}
