//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilegio
    {
        public int IdPrivilegio { get; set; }
        public string Descripcion { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public int Estado { get; set; }
    
        public virtual CuentaUsuario CuentaUsuario { get; set; }
    }
}
